object Versions {
    const val gradle = "7.0.2"
    const val kotlin = "1.5.30"
    const val material = "1.4.0"
    const val jacoco = "0.8.7"
    const val junit = "4.13.2"
    const val androidTest = "1.4.0"
    const val ktLint = "10.2.0"
    const val detekt = "1.18.1"
    const val compose = "1.0.3"
    const val activity = "1.3.1"
    const val apolloClient = "2.5.9"
    const val okHttp = "4.9.2"
    const val mockk = "1.12.0"
    const val coil = "1.3.1"
    const val archTesting = "2.1.0"
    const val easyPermissions = "1.0.0"
    const val servicesLocation = "18.0.0"
    const val composeNavigation = "2.4.0-alpha10"
}
